"""
Remediation API routes.

Script generation in this module is best-effort: the Finding model only
stores a single freeform `remediation_steps` text field and a JSONB
`evidence` blob — there are no dedicated az_cli_script/powershell_script/
terraform_block columns on Finding (those per-script-type fields live on
the separate Recommendation table, which scanners don't currently
populate). Until scanners are extended to write Recommendation rows,
script generation here falls back to emitting the remediation_steps text
as a commented action item rather than a ready-to-run command — this is
accurate to what data actually exists, rather than fabricating commands
that were never generated by a scanner.

RemediationTask tracks the *approval/execution lifecycle* for a finding's
remediation (pending -> approved -> running -> completed/failed/rejected)
via the execution_method field ("manual", "powershell", "cli", "terraform")
— it has no "action" column since the action is implied by finding_id.
"""
import logging
from uuid import UUID
from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload
import io

from backend.api.dependencies.auth import require_analyst
from backend.api.dependencies.database import get_db
from backend.models.models import Finding, RemediationTask, User

logger = logging.getLogger(__name__)
router = APIRouter(tags=["remediation"])


class RemediationRequest(BaseModel):
    finding_ids: list[UUID]
    script_type: str = "cli"  # cli | powershell | terraform


@router.post("/generate-scripts")
async def generate_remediation_scripts(
    body: RemediationRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_analyst),
) -> StreamingResponse:
    """
    Generate a remediation action checklist for selected findings.

    Returns a downloadable text file. Where evidence contains scanner-
    provided detail (e.g. resource IDs), that's included verbatim; the
    rest is the finding's remediation_steps guidance for an operator to
    act on manually, since no executable script is persisted per-finding
    in the current schema.
    """
    allowed_types = {"cli", "powershell", "terraform"}
    if body.script_type not in allowed_types:
        raise HTTPException(status_code=400, detail=f"script_type must be one of: {allowed_types}")
    if len(body.finding_ids) > 100:
        raise HTTPException(status_code=400, detail="Cannot generate scripts for more than 100 findings at once")

    result = await db.execute(
        select(Finding)
        .options(selectinload(Finding.resource))
        .where(Finding.id.in_(body.finding_ids))
    )
    findings = result.scalars().all()
    if not findings:
        raise HTTPException(status_code=404, detail="No findings found")

    script = _build_checklist(findings, body.script_type)
    ext = {"cli": "sh", "powershell": "ps1", "terraform": "tf"}[body.script_type]
    media_type = "text/x-shellscript" if body.script_type == "cli" else "text/plain"

    return StreamingResponse(
        io.BytesIO(script.encode("utf-8")),
        media_type=media_type,
        headers={
            "Content-Disposition": f'attachment; filename="arg-remediation-{datetime.now().strftime("%Y%m%d")}.{ext}"'
        },
    )


def _build_checklist(findings: list, script_type: str) -> str:
    """
    Generate a real, runnable remediation script for the selected findings.

    Structure per finding:
    - Header comment (finding title, severity, resource ID)
    - Remediation guidance (commented — for the operator to understand
      what the command does before running it)
    - The actual runnable command(s) from the scanner, uncommented and
      ready to execute

    For findings where the scanner didn't produce a script (identity
    findings, governance policy checks etc.), a clear placeholder with
    the Portal URL and manual steps is included instead, so the output
    is still useful rather than silently empty for those items.
    """
    now = datetime.now().strftime('%Y-%m-%d %H:%M UTC')

    if script_type == "powershell":
        shebang = ""
        header_comment = "#"
        line_comment = "#"
    elif script_type == "terraform":
        # Terraform has no delete/update resources by itself — generated
        # output is a shell script that operators can run to remove
        # resources that Terraform doesn't manage, after reviewing.
        shebang = "#!/usr/bin/env bash\nset -euo pipefail\n"
        header_comment = "#"
        line_comment = "#"
    else:  # cli / bash
        shebang = "#!/usr/bin/env bash\nset -euo pipefail\n"
        header_comment = "#"
        line_comment = "#"

    lines = [
        shebang,
        f"{header_comment} ============================================================",
        f"{header_comment} Azure Resource Guardian — Remediation Script",
        f"{header_comment} Generated: {now}",
        f"{header_comment} Mode: {script_type.upper()}",
        f"{header_comment} Findings: {len(findings)}",
        f"{header_comment} ============================================================",
        f"{header_comment}",
        f"{header_comment} ⚠️  REVIEW EVERY COMMAND BEFORE RUNNING.",
        f"{header_comment} Test in a non-production subscription first.",
        f"{header_comment} These commands make real changes to Azure resources.",
        "",
    ]

    for f in findings:
        sev = f.severity.value if hasattr(f.severity, "value") else f.severity
        resource_name = f.resource.resource_name if f.resource else "unknown"
        resource_id = f.resource.azure_resource_id if f.resource else None
        resource_group = f.resource.resource_group if f.resource else None
        subscription_id = str(f.subscription_id)

        lines.append(f"{line_comment} {'=' * 60}")
        lines.append(f"{line_comment} [{sev.upper()}] {f.title}")
        lines.append(f"{line_comment} Resource:     {resource_name}")
        if resource_id:
            lines.append(f"{line_comment} Resource ID:  {resource_id}")
        if resource_group:
            lines.append(f"{line_comment} Group:        {resource_group}")
        lines.append(f"{line_comment} Subscription: {subscription_id}")
        lines.append(f"{line_comment}")

        # Add remediation guidance as comments so the operator knows
        # what each command block is doing before they run it.
        if f.remediation_steps:
            lines.append(f"{line_comment} Guidance:")
            for step in f.remediation_steps.strip().splitlines():
                lines.append(f"{line_comment}   {step}")
            lines.append(f"{line_comment}")

        # Now add the actual runnable command(s).
        has_script = False
        if script_type == "powershell" and f.powershell_script:
            lines.append(f"{line_comment} --- Commands ---")
            for cmd_line in f.powershell_script.strip().splitlines():
                lines.append(cmd_line)  # real command, not a comment
            has_script = True
        elif script_type in ("cli", "terraform") and f.azure_cli_script:
            lines.append(f"{line_comment} --- Commands ---")
            for cmd_line in f.azure_cli_script.strip().splitlines():
                lines.append(cmd_line)  # real command, not a comment
            has_script = True

        if not has_script:
            # No machine-generated script for this finding type (identity
            # checks, policy config etc. that require manual Portal steps).
            # Include a direct Portal link and clear manual instructions.
            lines.append(f"{line_comment} No automated command available for this finding type.")
            lines.append(f"{line_comment} Remediate manually via the Azure Portal:")
            if resource_id:
                portal_url = f"https://portal.azure.com/#resource{resource_id}"
                lines.append(f"{line_comment}   {portal_url}")
            else:
                lines.append(f"{line_comment}   https://portal.azure.com/#blade/HubsExtension/BrowseAll")

        lines.append("")

    lines.append(f"{line_comment} End of remediation script — {len(findings)} finding(s) covered.")
    return "\n".join(lines)


@router.get("/tasks", response_model=dict)
async def list_remediation_tasks(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_analyst),
) -> dict:
    """List staged remediation tasks awaiting approval or execution."""
    result = await db.execute(
        select(RemediationTask)
        .options(selectinload(RemediationTask.finding))
        .order_by(RemediationTask.scheduled_at.desc().nullslast())
        .limit(100)
    )
    tasks = result.scalars().all()
    return {
        "items": [
            {
                "id": str(t.id),
                "finding_id": str(t.finding_id),
                "finding_title": t.finding.title if t.finding else None,
                "status": t.status.value if hasattr(t.status, "value") else t.status,
                "execution_method": t.execution_method,
                "notes": t.notes,
                "scheduled_at": t.scheduled_at,
                "executed_at": t.executed_at,
                "completed_at": t.completed_at,
            }
            for t in tasks
        ]
    }
