"""
Reports API routes — generate and download governance reports.

Finding resource details are pulled from the joined ResourceInventory
row (Finding has no resource_name/type/group/location columns of its
own). Every report generated via POST /generate is now both streamed
back immediately AND persisted (file on disk + a Report row), so it
shows up in GET /reports history and can be re-downloaded later via
GET /reports/{id}/download — previously generated reports were
streamed and discarded with no Report row ever created, which is why
the Reports history page always showed empty regardless of how many
reports had actually been generated.
"""
import logging
import os
import hashlib
from uuid import UUID
from datetime import datetime, timedelta, timezone

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse, FileResponse
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload
import io

from backend.core.config import settings
from backend.api.dependencies.auth import require_analyst
from backend.api.dependencies.database import get_db
from backend.models.models import Finding, Report, ReportFormat, FindingStatus, User
from backend.services.report_service import ReportService

logger = logging.getLogger(__name__)
router = APIRouter(tags=["reports"])
_report_service = ReportService()


class ReportRequest(BaseModel):
    report_type: str = "technical"      # executive | technical | board
    output_format: str = "pdf"          # pdf | excel | csv | json
    title: str | None = None
    subscription_ids: list[UUID] | None = None
    include_resolved: bool = False


@router.post("/generate")
async def generate_report(
    body: ReportRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_analyst),
) -> StreamingResponse:
    """Generate and stream a governance report directly — no DB row created."""
    allowed_formats = {"pdf", "excel", "csv", "json"}
    if body.output_format not in allowed_formats:
        raise HTTPException(status_code=400, detail=f"Format must be one of: {allowed_formats}")

    q = select(Finding).options(selectinload(Finding.resource))
    if not body.include_resolved:
        q = q.where(Finding.status.in_([FindingStatus.OPEN, FindingStatus.ACKNOWLEDGED]))
    if body.subscription_ids:
        q = q.where(Finding.subscription_id.in_(body.subscription_ids))
    q = q.order_by(Finding.severity.asc())

    result = await db.execute(q)
    findings = result.scalars().all()

    def sev_val(f: Finding) -> str:
        return f.severity.value if hasattr(f.severity, "value") else f.severity

    def status_val(f: Finding) -> str:
        return f.status.value if hasattr(f.status, "value") else f.status

    findings_data = [
        {
            "id": str(f.id),
            "severity": sev_val(f),
            "title": f.title,
            "description": f.description,
            "resource_name": f.resource.resource_name if f.resource else None,
            "resource_type": f.resource.resource_type if f.resource else None,
            "resource_id": f.resource.azure_resource_id if f.resource else None,
            "subscription_id": str(f.subscription_id),
            "resource_group": f.resource.resource_group if f.resource else None,
            "location": f.resource.location if f.resource else None,
            "category": f.category,
            "status": status_val(f),
            "estimated_monthly_saving": float(f.estimated_monthly_savings_usd or 0),
            "recommendation": f.remediation_steps,
            "detected_at": f.last_detected_at,
        }
        for f in findings
    ]

    title = body.title or f"Azure Resource Guardian — {body.report_type.title()} Report"
    summary = {
        "Total Findings": len(findings_data),
        "Critical": sum(1 for f in findings_data if f["severity"] == "critical"),
        "High": sum(1 for f in findings_data if f["severity"] == "high"),
        "Potential Monthly Savings": f"${sum(f['estimated_monthly_saving'] for f in findings_data):,.2f}",
        "Generated By": current_user.email,
        "Report Type": body.report_type.title(),
    }

    if body.output_format == "pdf":
        content = _report_service.generate_pdf(
            findings=findings_data, summary=summary, title=title, report_type=body.report_type,
        )
        media_type = "application/pdf"
        ext = "pdf"
        report_format = ReportFormat.PDF
    elif body.output_format == "excel":
        content = _report_service.generate_excel(findings=findings_data, summary=summary, title=title)
        media_type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        ext = "xlsx"
        report_format = ReportFormat.EXCEL
    elif body.output_format == "csv":
        content = _report_service.generate_csv(findings_data)
        media_type = "text/csv"
        ext = "csv"
        report_format = ReportFormat.CSV
    else:  # json
        content = _report_service.generate_json({"summary": summary, "findings": findings_data})
        media_type = "application/json"
        ext = "json"
        report_format = ReportFormat.JSON

    # Persist the file and a Report row so this shows up in GET /reports
    # history and can be re-downloaded later, instead of being streamed
    # once and discarded.
    os.makedirs(settings.REPORT_STORAGE_PATH, exist_ok=True)
    report_row = Report(
        generated_by=current_user.id,
        report_type=body.report_type,
        format=report_format,
        title=title,
        scope={"subscription_ids": [str(s) for s in (body.subscription_ids or [])]},
        is_ready=True,
        expires_at=datetime.now(timezone.utc) + timedelta(days=settings.REPORT_RETENTION_DAYS),
    )
    db.add(report_row)
    await db.flush()  # populate report_row.id before using it in the filename

    filename = f"arg-report-{report_row.id}.{ext}"
    file_path = os.path.join(settings.REPORT_STORAGE_PATH, filename)
    with open(file_path, "wb") as f:
        f.write(content)

    report_row.file_path = file_path
    report_row.file_size_bytes = len(content)
    report_row.file_hash = hashlib.sha256(content).hexdigest()
    await db.commit()

    download_filename = f"arg-report-{datetime.now().strftime('%Y%m%d')}.{ext}"
    return StreamingResponse(
        io.BytesIO(content),
        media_type=media_type,
        headers={"Content-Disposition": f'attachment; filename="{download_filename}"'},
    )


@router.get("", response_model=dict)
async def list_reports(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_analyst),
) -> dict:
    """
    List previously generated reports — both on-demand (POST /generate)
    and scheduled (produced by the report worker, once implemented).
    Ordered by expiration since there's no created_at column —
    expires_at is the closest proxy for recency available on this table.
    """
    result = await db.execute(select(Report).order_by(Report.expires_at.desc()).limit(50))
    reports = result.scalars().all()
    return {
        "items": [
            {
                "id": str(r.id),
                "title": r.title,
                "report_type": r.report_type,
                "output_format": r.format.value if hasattr(r.format, "value") else r.format,
                "is_ready": r.is_ready,
                "error_message": r.error_message,
                "expires_at": r.expires_at,
                "file_size_bytes": r.file_size_bytes,
            }
            for r in reports
        ]
    }


@router.get("/{report_id}/download")
async def download_report(
    report_id: UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_analyst),
):
    """Re-download a previously generated report from history."""
    report = await db.get(Report, str(report_id))
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
    if not report.file_path or not os.path.exists(report.file_path):
        raise HTTPException(
            status_code=404,
            detail="Report file is no longer available — it may have expired and been cleaned up.",
        )

    media_types = {
        ReportFormat.PDF: "application/pdf",
        ReportFormat.EXCEL: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        ReportFormat.CSV: "text/csv",
        ReportFormat.JSON: "application/json",
    }
    ext_map = {ReportFormat.PDF: "pdf", ReportFormat.EXCEL: "xlsx", ReportFormat.CSV: "csv", ReportFormat.JSON: "json"}
    fmt = report.format if isinstance(report.format, ReportFormat) else ReportFormat(report.format)

    return FileResponse(
        report.file_path,
        media_type=media_types.get(fmt, "application/octet-stream"),
        filename=f"{report.title}.{ext_map.get(fmt, 'bin')}",
    )


@router.delete("/{report_id}", status_code=204)
async def delete_report(
    report_id: UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_analyst),
):
    """Delete a report's file and its history entry."""
    report = await db.get(Report, str(report_id))
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")

    if report.file_path and os.path.exists(report.file_path):
        try:
            os.remove(report.file_path)
        except OSError as exc:
            logger.warning(f"Failed to remove report file {report.file_path}: {exc}")

    await db.delete(report)
    await db.commit()
