"""
Regenerate docs/scanner-catalog.md from the scanner registry.

    python -m scripts.generate_scanner_catalog     (from the repository root)

Run it after adding or changing a scanner or a finding type, so the catalog never
drifts from the code. Data sources are inferred from each scanner's source.
"""

import inspect
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from scanners.base.base_scanner import ScannerRegistry  # noqa: E402
from scripts.subscription_analysis.collector import load_scanners  # noqa: E402
from scripts.subscription_analysis.knowledge import WAVE_NAMES, classify  # noqa: E402

SOURCE_MARKERS = [
    ("Resource Graph", ("resource_graph", "self.arg(", "_run_arg_query")),
    ("Azure Monitor metrics", ("metrics",)),
    ("Cost Management", ("get_resource_costs", "run_cost_query", "requires_cost = True")),
    ("ARM REST", ("arm_client", "arm.get")),
    ("Defender for Cloud", ("securityresources", "get_defender_plans")),
    ("Advisor", ("advisorresources",)),
    ("RBAC", ("authorizationresources",)),
]


def build() -> str:
    load_scanners()
    rows = []
    for name, cls in sorted(ScannerRegistry.all().items(), key=lambda kv: (kv[1].category.value, kv[0])):
        src = inspect.getsource(cls)
        types = sorted(set(re.findall(r'finding_type="([a-z0-9_]+)"', src)))
        sources = [label for label, markers in SOURCE_MARKERS if any(m in src for m in markers)]
        if cls.requires_graph:
            sources = ["Microsoft Graph"]
        if "terraform_state" in src:
            sources = ["Imported Terraform state"]
        rows.append((cls.category.value, name, cls.display_name, cls.severity.value, types, sources, cls.requires_graph))

    all_types = sorted({t for r in rows for t in r[4]})
    out = ["# Scanner Catalog", "",
           "Every scanner registered in ARG, generated by `python -m scripts.generate_scanner_catalog` (regenerate after",
           "adding or changing a scanner). The **Local** column shows whether the scanner runs in the CLI / local portal",
           "(`az login`). Microsoft Graph scanners need the Docker stack with a service principal and Graph consent.", "",
           f"Total: **{len(rows)} scanners**, **{len(all_types)} finding types**.", ""]
    category = None
    for cat, name, display, severity, types, sources, graph in rows:
        if cat != category:
            out += ["", f"## {cat.title()}", "",
                    "| Scanner | What it detects | Default severity | Finding types | Data sources | Local |",
                    "|---|---|---|---|---|---|"]
            category = cat
        out.append(f"| `{name}` | {display} | {severity} | " + "<br>".join(f"`{t}`" for t in types)
                   + f" | {', '.join(sources)} | {'no' if graph else 'yes'} |")
    out += ["", "## Finding type → report placement", "",
            "How the subscription analysis report files each finding type (gap-analysis area, deep-dive folder, savings wave).",
            "", "| Finding type | Gap area | Deep-dive folder | Wave |", "|---|---|---|---|"]
    for t in all_types:
        k = classify(t, "")
        out.append(f"| `{t}` | {k.area} | `{k.folder}` | {WAVE_NAMES[k.wave]} |")
    return "\n".join(out) + "\n"


def main() -> int:
    target = REPO_ROOT / "docs" / "scanner-catalog.md"
    target.write_text(build(), encoding="utf-8", newline="\n")
    print(f"Wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
