"""score_snapshots

Revision ID: b5f5fbaa4ed8
Revises: 62cbdf34f62b
Create Date: 2026-06-21 16:37:44.281572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5f5fbaa4ed8'
down_revision: Union[str, None] = '62cbdf34f62b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_snapshots',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('subscription_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('governance_score', sa.Integer(), nullable=False),
    sa.Column('security_score', sa.Integer(), nullable=False),
    sa.Column('identity_score', sa.Integer(), nullable=True),
    sa.Column('total_findings_open', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'snapshot_date', name='uq_score_snapshot_sub_date')
    )
    op.create_index(op.f('ix_score_snapshots_snapshot_date'), 'score_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_score_snapshots_subscription_id'), 'score_snapshots', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_snapshots_subscription_id'), table_name='score_snapshots')
    op.drop_index(op.f('ix_score_snapshots_snapshot_date'), table_name='score_snapshots')
    op.drop_table('score_snapshots')
    # ### end Alembic commands ###
