"""initial schema

Revision ID: ee37468fb4ea
Revises: 
Create Date: 2026-06-19 20:25:54.818256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee37468fb4ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scanner_plugins',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('plugin_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('module_path', sa.String(length=500), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('requires_graph', sa.Boolean(), nullable=True),
    sa.Column('requires_cost', sa.Boolean(), nullable=True),
    sa.Column('config_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avg_duration_ms', sa.Integer(), nullable=True),
    sa.Column('total_runs', sa.Integer(), nullable=True),
    sa.Column('total_findings', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scanner_plugins_category', 'scanner_plugins', ['category'], unique=False)
    op.create_index(op.f('ix_scanner_plugins_is_enabled'), 'scanner_plugins', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_scanner_plugins_plugin_name'), 'scanner_plugins', ['plugin_name'], unique=True)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('client_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('management_group_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('graph_permissions_granted', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tenants_active', 'tenants', ['is_active'], unique=False)
    op.create_index(op.f('ix_tenants_tenant_id'), 'tenants', ['tenant_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'ANALYST', 'VIEWER', 'AUDITOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('sso_provider', sa.String(length=50), nullable=True),
    sa.Column('sso_subject', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_active', 'users', ['email'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_user_action', 'audit_logs', ['user_id', 'action'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('ix_refresh_tokens_user_active', 'refresh_tokens', ['user_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('management_group_id', sa.String(length=255), nullable=True),
    sa.Column('offer_type', sa.String(length=50), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('monthly_budget_usd', sa.Float(), nullable=True),
    sa.Column('governance_score', sa.Float(), nullable=True),
    sa.Column('security_score', sa.Float(), nullable=True),
    sa.Column('identity_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_management_group_id'), 'subscriptions', ['management_group_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_subscription_id'), 'subscriptions', ['subscription_id'], unique=True)
    op.create_index('ix_subscriptions_tenant', 'subscriptions', ['tenant_id'], unique=False)
    op.create_table('scan_jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('subscription_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('triggered_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='scanstatus'), nullable=False),
    sa.Column('scanners_requested', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scan_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('total_resources_scanned', sa.Integer(), nullable=False),
    sa.Column('total_findings', sa.Integer(), nullable=False),
    sa.Column('findings_by_severity', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_jobs_celery_task_id'), 'scan_jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_scan_jobs_status'), 'scan_jobs', ['status'], unique=False)
    op.create_index('ix_scan_jobs_status_created', 'scan_jobs', ['status', 'created_at'], unique=False)
    op.create_index('ix_scan_jobs_subscription', 'scan_jobs', ['subscription_id'], unique=False)
    op.create_table('terraform_states',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('subscription_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_name', sa.String(length=255), nullable=False),
    sa.Column('state_file_path', sa.Text(), nullable=True),
    sa.Column('backend_type', sa.String(length=50), nullable=True),
    sa.Column('backend_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('terraform_version', sa.String(length=20), nullable=True),
    sa.Column('resource_count', sa.Integer(), nullable=True),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('drift_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_drift_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('managed_count', sa.Integer(), nullable=True),
    sa.Column('unmanaged_count', sa.Integer(), nullable=True),
    sa.Column('missing_count', sa.Integer(), nullable=True),
    sa.Column('drifted_count', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'workspace_name', name='uq_tf_state_workspace')
    )
    op.create_table('entra_findings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scan_job_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('object_id', sa.String(length=36), nullable=False),
    sa.Column('object_display_name', sa.String(length=255), nullable=True),
    sa.Column('object_upn', sa.String(length=255), nullable=True),
    sa.Column('finding_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severitylevel'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'SUPPRESSED', 'FALSE_POSITIVE', name='findingstatus'), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_sign_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entra_findings_finding_type'), 'entra_findings', ['finding_type'], unique=False)
    op.create_index(op.f('ix_entra_findings_object_id'), 'entra_findings', ['object_id'], unique=False)
    op.create_index(op.f('ix_entra_findings_object_type'), 'entra_findings', ['object_type'], unique=False)
    op.create_index(op.f('ix_entra_findings_severity'), 'entra_findings', ['severity'], unique=False)
    op.create_index('ix_entra_findings_severity_status', 'entra_findings', ['severity', 'status'], unique=False)
    op.create_index('ix_entra_findings_tenant_type', 'entra_findings', ['tenant_id', 'object_type'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('generated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('scan_job_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('format', sa.Enum('PDF', 'CSV', 'EXCEL', 'JSON', name='reportformat'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('date_range_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_range_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_is_ready'), 'reports', ['is_ready'], unique=False)
    op.create_table('resource_inventory',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('subscription_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('azure_resource_id', sa.Text(), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=255), nullable=False),
    sa.Column('resource_group', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('sku', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('owner_tag', sa.String(length=255), nullable=True),
    sa.Column('environment_tag', sa.String(length=100), nullable=True),
    sa.Column('cost_center_tag', sa.String(length=100), nullable=True),
    sa.Column('azure_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('azure_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_orphaned', sa.Boolean(), nullable=False),
    sa.Column('monthly_cost_usd', sa.Float(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terraform_managed', sa.Boolean(), nullable=True),
    sa.Column('drift_status', sa.Enum('MANAGED', 'UNMANAGED', 'MISSING', 'DRIFTED', name='driftstatus'), nullable=True),
    sa.Column('first_seen_scan_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('last_seen_scan_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['first_seen_scan_id'], ['scan_jobs.id'], ),
    sa.ForeignKeyConstraint(['last_seen_scan_id'], ['scan_jobs.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'azure_resource_id', name='uq_resource_subscription')
    )
    op.create_index('ix_inventory_orphaned', 'resource_inventory', ['is_orphaned'], unique=False, postgresql_where=sa.text('is_orphaned = TRUE'))
    op.create_index('ix_inventory_rg_sub', 'resource_inventory', ['resource_group', 'subscription_id'], unique=False)
    op.create_index('ix_inventory_type_sub', 'resource_inventory', ['resource_type', 'subscription_id'], unique=False)
    op.create_index(op.f('ix_resource_inventory_drift_status'), 'resource_inventory', ['drift_status'], unique=False)
    op.create_index(op.f('ix_resource_inventory_is_orphaned'), 'resource_inventory', ['is_orphaned'], unique=False)
    op.create_index(op.f('ix_resource_inventory_location'), 'resource_inventory', ['location'], unique=False)
    op.create_index(op.f('ix_resource_inventory_resource_group'), 'resource_inventory', ['resource_group'], unique=False)
    op.create_index(op.f('ix_resource_inventory_resource_type'), 'resource_inventory', ['resource_type'], unique=False)
    op.create_table('scan_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scan_job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scanner_name', sa.String(length=100), nullable=False),
    sa.Column('scanner_version', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='scanstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('resources_scanned', sa.Integer(), nullable=True),
    sa.Column('findings_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scan_results_job_scanner', 'scan_results', ['scan_job_id', 'scanner_name'], unique=False)
    op.create_index(op.f('ix_scan_results_scan_job_id'), 'scan_results', ['scan_job_id'], unique=False)
    op.create_table('cost_savings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('subscription_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('resource_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('opportunity_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.String(length=255), nullable=True),
    sa.Column('resource_name', sa.String(length=255), nullable=True),
    sa.Column('resource_group', sa.String(length=255), nullable=True),
    sa.Column('current_monthly_cost_usd', sa.Float(), nullable=False),
    sa.Column('estimated_monthly_savings_usd', sa.Float(), nullable=False),
    sa.Column('estimated_annual_savings_usd', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('action_required', sa.String(length=100), nullable=False),
    sa.Column('effort', sa.String(length=20), nullable=False),
    sa.Column('risk', sa.String(length=20), nullable=False),
    sa.Column('is_actioned', sa.Boolean(), nullable=False),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_savings_usd', sa.Float(), nullable=True),
    sa.Column('first_identified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_inventory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cost_savings_amount', 'cost_savings', ['estimated_monthly_savings_usd'], unique=False)
    op.create_index(op.f('ix_cost_savings_opportunity_type'), 'cost_savings', ['opportunity_type'], unique=False)
    op.create_index('ix_cost_savings_sub_type', 'cost_savings', ['subscription_id', 'opportunity_type'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('subscription_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('resource_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('scan_job_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('finding_type', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severitylevel'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('remediation_steps', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'SUPPRESSED', 'FALSE_POSITIVE', name='findingstatus'), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suppressed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suppression_reason', sa.Text(), nullable=True),
    sa.Column('estimated_monthly_savings_usd', sa.Float(), nullable=True),
    sa.Column('estimated_annual_savings_usd', sa.Float(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affected_resources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('caf_control', sa.String(length=100), nullable=True),
    sa.Column('nist_control', sa.String(length=100), nullable=True),
    sa.Column('cis_control', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_inventory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_category'), 'findings', ['category'], unique=False)
    op.create_index('ix_findings_category_sub', 'findings', ['category', 'subscription_id'], unique=False)
    op.create_index(op.f('ix_findings_finding_type'), 'findings', ['finding_type'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index('ix_findings_severity_status', 'findings', ['severity', 'status'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_index('ix_findings_type_resource', 'findings', ['finding_type', 'resource_id'], unique=False)
    op.create_table('resource_costs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('resource_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('billing_month', sa.String(length=7), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=True),
    sa.Column('meter_category', sa.String(length=255), nullable=True),
    sa.Column('usage_quantity', sa.Float(), nullable=True),
    sa.Column('usage_unit', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_inventory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'billing_month', name='uq_resource_cost_month')
    )
    op.create_index('ix_resource_costs_month', 'resource_costs', ['billing_month'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('finding_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('subscription_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('effort', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('powershell_script', sa.Text(), nullable=True),
    sa.Column('azure_cli_script', sa.Text(), nullable=True),
    sa.Column('terraform_hcl', sa.Text(), nullable=True),
    sa.Column('arm_template', sa.Text(), nullable=True),
    sa.Column('estimated_savings_monthly_usd', sa.Float(), nullable=True),
    sa.Column('is_automated', sa.Boolean(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remediation_tasks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('finding_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('assigned_to', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('approved_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'RUNNING', 'COMPLETED', 'FAILED', 'REJECTED', name='remediationstatus'), nullable=False),
    sa.Column('execution_method', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_log', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_tasks_status'), 'remediation_tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remediation_tasks_status'), table_name='remediation_tasks')
    op.drop_table('remediation_tasks')
    op.drop_table('recommendations')
    op.drop_index('ix_resource_costs_month', table_name='resource_costs')
    op.drop_table('resource_costs')
    op.drop_index('ix_findings_type_resource', table_name='findings')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index('ix_findings_severity_status', table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_finding_type'), table_name='findings')
    op.drop_index('ix_findings_category_sub', table_name='findings')
    op.drop_index(op.f('ix_findings_category'), table_name='findings')
    op.drop_table('findings')
    op.drop_index('ix_cost_savings_sub_type', table_name='cost_savings')
    op.drop_index(op.f('ix_cost_savings_opportunity_type'), table_name='cost_savings')
    op.drop_index('ix_cost_savings_amount', table_name='cost_savings')
    op.drop_table('cost_savings')
    op.drop_index(op.f('ix_scan_results_scan_job_id'), table_name='scan_results')
    op.drop_index('ix_scan_results_job_scanner', table_name='scan_results')
    op.drop_table('scan_results')
    op.drop_index(op.f('ix_resource_inventory_resource_type'), table_name='resource_inventory')
    op.drop_index(op.f('ix_resource_inventory_resource_group'), table_name='resource_inventory')
    op.drop_index(op.f('ix_resource_inventory_location'), table_name='resource_inventory')
    op.drop_index(op.f('ix_resource_inventory_is_orphaned'), table_name='resource_inventory')
    op.drop_index(op.f('ix_resource_inventory_drift_status'), table_name='resource_inventory')
    op.drop_index('ix_inventory_type_sub', table_name='resource_inventory')
    op.drop_index('ix_inventory_rg_sub', table_name='resource_inventory')
    op.drop_index('ix_inventory_orphaned', table_name='resource_inventory', postgresql_where=sa.text('is_orphaned = TRUE'))
    op.drop_table('resource_inventory')
    op.drop_index(op.f('ix_reports_is_ready'), table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_entra_findings_tenant_type', table_name='entra_findings')
    op.drop_index('ix_entra_findings_severity_status', table_name='entra_findings')
    op.drop_index(op.f('ix_entra_findings_severity'), table_name='entra_findings')
    op.drop_index(op.f('ix_entra_findings_object_type'), table_name='entra_findings')
    op.drop_index(op.f('ix_entra_findings_object_id'), table_name='entra_findings')
    op.drop_index(op.f('ix_entra_findings_finding_type'), table_name='entra_findings')
    op.drop_table('entra_findings')
    op.drop_table('terraform_states')
    op.drop_index('ix_scan_jobs_subscription', table_name='scan_jobs')
    op.drop_index('ix_scan_jobs_status_created', table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_status'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_celery_task_id'), table_name='scan_jobs')
    op.drop_table('scan_jobs')
    op.drop_index('ix_subscriptions_tenant', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_management_group_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_refresh_tokens_user_active', table_name='refresh_tokens', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_audit_logs_user_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_email_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_tenant_id'), table_name='tenants')
    op.drop_index('ix_tenants_active', table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_scanner_plugins_plugin_name'), table_name='scanner_plugins')
    op.drop_index(op.f('ix_scanner_plugins_is_enabled'), table_name='scanner_plugins')
    op.drop_index('ix_scanner_plugins_category', table_name='scanner_plugins')
    op.drop_table('scanner_plugins')
    # ### end Alembic commands ###
