"""finding_script_columns

Revision ID: fa8a02aaaed8
Revises: b5f5fbaa4ed8
Create Date: 2026-06-22 19:51:17.579943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa8a02aaaed8'
down_revision: Union[str, None] = 'b5f5fbaa4ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Use IF NOT EXISTS because the initial schema migration (ee37468fb4ea)
    # already includes these columns in the CREATE TABLE findings statement.
    # On a fresh install, alembic upgrade head would run both migrations and
    # the plain ADD COLUMN would fail with "column already exists". On a live
    # database from an older build where the initial schema didn't have these
    # columns, the IF NOT EXISTS is a no-op and the column gets added normally.
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing = {c['name'] for c in inspector.get_columns('findings')}
    if 'azure_cli_script' not in existing:
        op.add_column('findings', sa.Column('azure_cli_script', sa.Text(), nullable=True))
    if 'powershell_script' not in existing:
        op.add_column('findings', sa.Column('powershell_script', sa.Text(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'powershell_script')
    op.drop_column('findings', 'azure_cli_script')
    # ### end Alembic commands ###
